"""Description of the migration

Revision ID: 0435003b3cfc
Revises: 1d07f7cd4fdc
Create Date: 2023-06-23 12:29:01.586751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0435003b3cfc'
down_revision = '1d07f7cd4fdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###
