"""Description of the migration

Revision ID: 1d07f7cd4fdc
Revises: e1606baa92ba
Create Date: 2023-06-23 12:27:35.345121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d07f7cd4fdc'
down_revision = 'e1606baa92ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
      op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('fullname', sa.String(), index=True),
        sa.Column('email', sa.String(), unique=True, index=True),
        sa.Column('phone', sa.String(), unique=True, index=True),
        sa.Column('password', sa.String()),
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
