"""Description of the migration

Revision ID: e1606baa92ba
Revises: 3e1e3c2ef5e0
Create Date: 2023-06-23 12:21:29.204952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1606baa92ba'
down_revision = '3e1e3c2ef5e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
